### ISSUE TITLE
Writing direclty to the output stream

### ISSUE THREAD

**Issue by kayhman** [fukamachi/woo#25]
Hi,

I'd like to benchmark woo in my use case, but I need to be able to write directly to the output stream (as the json data that I return can be large).

Is there a way to access this output stream (as in hunchentoot) ? 

Thanks,

guillaume

**Comment by fukamachi** [comment]
Woo doesn't provide stream interface for responding since Clack/Lack doesn't.

Because "stream" is slow in Common Lisp, Clack/Lack doesn't allow to access a response stream. Clack/Lack abstracts it as an anonymous function and it can also be applied to Woo. See Lack's README:
https://github.com/fukamachi/lack#delayed-response-and-streaming-body

**Comment by kayhman** [comment]
Thanks,

This is exaclty what I was looking for.

Regards,

Guillaume
